### ISSUE TITLE
Geolocation fallback

### ISSUE THREAD

**Issue by hkdobrev** [hkdobrev/setmap#1]
When you set option "current" to true in order to use HTML5 Geolocation the fallback is not working.

If the user does not allow the geolocation the plugin is using $.error to log this. This is stopping the execution of the callback and the map is not initialized.

**Comment by rcahuich** [comment]
I have this error, I've been testing in the map-with-geocoding am new to this, which is what is happening? please

Uncaught Error: Method setAddress does not exist on the setmap plugin!

**Comment by hkdobrev** [comment]
This is not a relevant problem anymore since version [`2.0.0-alpha.1`](https://github.com/hkdobrev/setmap/releases/tag/2.0.0-alpha.1).
