### ISSUE TITLE
Better geolocation

### ISSUE THREAD

**Issue by hkdobrev** [hkdobrev/setmap#2]
It should be possible to initialize the map and then set the location to the current location.

It would also be great an asynchronous geolocation to be available.

**Comment by rcahuich** [comment]
I have this error, I've been testing in the map-with-geocoding am new to this, which is what is happening? please

Uncaught Error: Method setAddress does not exist on the setmap plugin!

**Comment by hkdobrev** [comment]
The thing is that the demos are for version 1.0 and are not compatible with version 2.0.

This is version 2.0 and 1.0 is available on [CodeCanyon](http://codecanyon.net/item/setmap-jquery-plugin-for-google-maps/743337) and has fewer features.

I really don't have time to write Documentation and new demos right now, but I am going to in the near future.

Your particular problem has nothing to do with this issue, but rather with this one: https://github.com/hkdobrev/setmap/issues/3

**Comment by hkdobrev** [comment]
This is now fixed in version [`2.0.0-alpha.1`](https://github.com/hkdobrev/setmap/releases/tag/2.0.0-alpha.1).
